//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopTal.JoggingApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TopTal.JoggingApp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials!|No user can be found with the specified username and password. Please, try again..
        /// </summary>
        public static string Account_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("Account_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out!|The specified account has been locked out. Please, contact the administrator..
        /// </summary>
        public static string Account_LockedOut {
            get {
                return ResourceManager.GetString("Account_LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed account!|The specified account has to be confirmed.  A confimation e-mail has been already sent. Please, check your inbox..
        /// </summary>
        public static string Account_RequiresVertification {
            get {
                return ResourceManager.GetString("Account_RequiresVertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found!|The requested entity was not found. (Entity: {1}, Key: {2}, Resource: {0}).
        /// </summary>
        public static string Entity_EntityNotFound {
            get {
                return ResourceManager.GetString("Entity_EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key error!|The specified entity key is invalid. (Entity: {1}, Key: {2}, Resource: {0}).
        /// </summary>
        public static string Entity_InvalidKey {
            get {
                return ResourceManager.GetString("Entity_InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much data!|Too much data would be returned. Please, specify a filter.  (Entity: {1}, Required filter: {2}, Resource: {0}).
        /// </summary>
        public static string Entity_TooMuchDataFilterRequited {
            get {
                return ResourceManager.GetString("Entity_TooMuchDataFilterRequited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured!|Please, report to the administrator. ({0}).
        /// </summary>
        public static string Error_GenericServerError {
            get {
                return ResourceManager.GetString("Error_GenericServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used e-mail address!|The selected e-mail address is already used. Please, enter a different address..
        /// </summary>
        public static string Register_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("Register_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthenticated!|You have to log in to access the requested resource. (Permission: {1}, Resource: {0}).
        /// </summary>
        public static string Security_Unauthenticated {
            get {
                return ResourceManager.GetString("Security_Unauthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized!|You don&apos;t have access to the requested resource. Please, contact the administrator. (Permission: {1}, Resource: {0}).
        /// </summary>
        public static string Security_Unauthorized {
            get {
                return ResourceManager.GetString("Security_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error!|{0} Please, correct the errors..
        /// </summary>
        public static string Validation_Error {
            get {
                return ResourceManager.GetString("Validation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect data!|Token validation failed. Please, reload the page..
        /// </summary>
        public static string Validation_InvalidAntiForgeryToken {
            get {
                return ResourceManager.GetString("Validation_InvalidAntiForgeryToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more mandatory fields are missing. Please, fill all mandatory fields before proceeding..
        /// </summary>
        public static string Validation_MandatoryFieldsAreMissing {
            get {
                return ResourceManager.GetString("Validation_MandatoryFieldsAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data!|Expected input data was missing.Please, provide correct input. (Data: {1}, Resource: {0}).
        /// </summary>
        public static string Validation_MissingInputData {
            get {
                return ResourceManager.GetString("Validation_MissingInputData", resourceCulture);
            }
        }
    }
}
